### ISSUE TITLE
Team still present after removal?

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mmctl#12]
Greetings I have made some teams in past that I had not needed and were merely a testing team, now when I wanted to tidy up the DB and server a bit, it seems this fails or is cached?

Normally after the removal of a team I expect a:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/6324047/60629103-ad80ef00-9df4-11e9-8e4f-047f1dae7f3b.png">

In my case the teams were still browsable from the app/browser.

```
➜ mmctl team delete open-source
Have you performed a database backup? (YES/NO): 
YES
Are you sure you want to delete the teams specified?  All data will be permanently deleted? (YES/NO): 
YES
Deleted team 'open-source'

00:31:16.799 in zsh-syntax-highlighting on  master took 26s 
➜ mmctl team list              
cloud
devops
netops
open-source
support

```
VersuS server CLI this it seems it removed the team.

```
[root@chat bin]# ./mattermost team list
cloud
devops
netops
open-source (archived)
support
[root@chat bin]# ./mattermost team delete open-source
Have you performed a database backup? (YES/NO): 
YES
Are you sure you want to delete the teams specified?  All data will be permanently deleted? (YES/NO): 
YES
Deleted team 'open-source'
[root@chat bin]# ./mattermost team list
cloud
devops
netops
support
[root@chat bin]# ./mattermost team list
```

**Comment by uhlhosting** [comment]
After running locally in server mattermost command, locally in my macbook i got:

```
00:44:45.529 in .oh-my-zsh/custom/plugins on  master 
➜ mmctl team list 
devops
netops
support
```

**Comment by mgdelacroix** [comment]
Thanks for the report, @uhlhosting. The `team delete` command uses the [delete team API endpoint](https://api.mattermost.com/#tag/teams%2Fpaths%2F~1teams~1%7Bteam_id%7D%2Fdelete) and tries to perform a permanent deletion.

The endpoint needs the `ServiceSettings.EnableAPITeamDeletion` config parameter to be set to true for the permanent deletion is allowed, if the parameter is set to false (which is the default behavior), the endpoint will archive the channel instead of deleting it. Can you please set that config parameter to `true` and try again?

To improve readability, I've submitted #13 to add `(archived)` to the archived teams in `team list`, so this behavior becomes more apparent.

**Comment by uhlhosting** [comment]
I had indeed on false. And indeed they were archived teams. A still unexpected was that alto the teams archived, one if knowing their address could browse them without trouble. 

Maybe a default page to show that the teams were archived and access request to browse them would help.

**Comment by isacikgoz** [comment]
This issue does not exhibit anymore, with the #13 improvement, we can now understand whether a team is archived or not.
