### ISSUE TITLE
Is mmctl version v6.4.1 compatible with mattermost 7.0.0?

### ISSUE THREAD

**Issue by gc-ss** [mattermost/mmctl#523]
mattermost 7.0.0 is due to be released June 15th (with Release candidate cut already): https://github.com/mattermost/mattermost-server/issues/20307

However, I don't see anything other than mmctl version v6.4.1 being packaged with mattermost 7.0.0: https://github.com/mattermost/mattermost-server/issues/20324

- Is mmctl version v6.4.1 compatible with mattermost 7.0.0? (currently I can't use mmctl version v6.4.1 with mattermost 7.0.0: https://github.com/mattermost/mattermost-server/issues/20324 but I could be making a mistake)
- If not, will a mmctl version that's compatible with mattermost 7.0.0 be released by June 15th?
- Also, is a mmctl version that's compatible with mattermost 7.0.0 already available for me to test with the Release candidate that's cut already?

**Comment by isacikgoz** [comment]
Hey @gc-ss there will be a major version difference hence we cannot guarantee it's going to work properly. Having said that mmctl 7.0 has a bug that preventing to work with any version of mattermost due to a version parsing issue (fixed [here](https://github.com/mattermost/mmctl/pull/529)). We recommend using `v70.1` instead.
