### ISSUE TITLE
Duplicate command `make-private` in channel

### ISSUE THREAD

**Issue by ChandanChainani** [mattermost/mmctl#575]
The same functionality is available through `modify` command which allow us to make channel private or public

> **I would love to work on the issue**

**Comment by isacikgoz** [comment]
Great point @ChandanChainani This is actually right. The reason why we kept both is to maintain backwards compatibility. Having said that, since you'd like to work on this. Would you mind adding a deprecation flag to the command? You should add https://pkg.go.dev/github.com/spf13/cobra#Command `Deprecated` string to the command.

**Comment by ChandanChainani** [comment]
@isacikgoz I have raised PR with suggested changes please review
