### ISSUE TITLE
Another macOS issue

### ISSUE THREAD

**Issue by jby** [mattermost/mmctl#9]
```
/usr/local/bin/go vet github.com/mattermost/mmctl github.com/mattermost/mmctl/commands
/usr/local/bin/go vet -vettool=/bin/shadow github.com/mattermost/mmctl github.com/mattermost/mmctl/commands
go vet: can't execute /bin/shadow -flags: fork/exec /bin/shadow: no such file or directory
make: *** [govet] Error 2
```
Don't know what /bin/shadow is supposed to do, but it's non-existent in macOS 10.14.5

**Comment by mgdelacroix** [comment]
I guess that this error is happening when running `make govet` or `make check`, right?

https://github.com/mattermost/mmctl/blob/master/Makefile#L49

Shadow is used as the `vettool` for `go vet`, and it's path is built with `$(GOPATH)/bin/shadow`. It is downloaded as part of the make task just right before the step that is throwing the error. From your output, it seems that you don't have the `GOPATH` environment variable set, and because of that the path for the `shadow` binary is incorrect.

Try to define the `GOPATH` variable either on your terminal startup file or directly on your terminal session before running the command again.

**Comment by jby** [comment]
> I guess that this error is happening when running `make govet` or `make check`, right?
Well, no, actually I'm running `make build` when I get this.
> https://github.com/mattermost/mmctl/blob/master/Makefile#L49
> 
> Shadow is used as the `vettool` for `go vet`, and it's path is built with `$(GOPATH)/bin/shadow`. It is downloaded as part of the make task just right before the step that is throwing the error. From your output, it seems that you don't have the `GOPATH` environment variable set, and because of that the path for the `shadow` binary is incorrect.
> 
> Try to define the `GOPATH` variable either on your terminal startup file or directly on your terminal session before running the command again.
Yes, I found $HOME/go/bin/shadow, so setting GOPATH to $HOME/go solved this.
